import { Footer, Header } from "./components";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Fylo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-[#181F2A] ${openSans.className} text-[14px]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
