import { ClerkProvider } from "@clerk/nextjs";
import { Footer, Header } from "./components";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Fylo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider appearance={
        {variables:{
          colorPrimary: "#0B1523"
        }}
      }>
        <body className={`bg-[#181F2A] ${openSans.className} text-[14px]`}>
          <Header />
          {children}
          <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
}
